// text names
export const tn = {
    email: 'email',
    password: 'password',
    login: 'login',
    signUp: 'signUp',
    username: 'username',
    groupChat: 'groupChat',
    startWriting: 'startWriting',
    settings: 'settings',
    colorTheme: 'colorTheme',
    dark: 'dark',
    light: 'light',
    language: 'language',
    english: 'english',
    turkish: 'turkish',
    signOut: 'signOut',
    newMessageFrom: 'newMessageFrom',
};

export const english = {
    [tn.email]: 'E-mail',
    [tn.password]: 'Password',
    [tn.login]: 'Login',
    [tn.signUp]: 'Sign Up',
    [tn.username]: 'Username',
    [tn.groupChat]: 'Group Chat',
    [tn.startWriting]: 'Start writing',
    [tn.settings]: 'Settings',
    [tn.colorTheme]: 'Color Theme',
    [tn.dark]: 'Dark',
    [tn.light]: 'Light',
    [tn.language]: 'Language',
    [tn.english]: 'English',
    [tn.turkish]: 'Türkçe',
    [tn.signOut]: 'Sign Out',
    [tn.newMessageFrom]: 'New message from %{senderName}',
}

export const turkish = {
    [tn.email]: 'E-posta',
    [tn.password]: 'Şifre',
    [tn.login]: 'Giriş Yap',
    [tn.signUp]: 'Kayıt Ol',
    [tn.username]: 'Kullanıcı Adı',
    [tn.groupChat]: 'Grup Sohbeti',
    [tn.startWriting]: 'Yazmaya başlayın...',
    [tn.settings]: 'Ayarlar',
    [tn.colorTheme]: 'Renk Teması',
    [tn.dark]: 'Karanlık',
    [tn.light]: 'Aydınlık',
    [tn.language]: 'Dil',
    [tn.english]: 'English',
    [tn.turkish]: 'Türkçe',
    [tn.signOut]: 'Çıkış Yap',
    [tn.newMessageFrom]: '%{senderName} yeni bir mesaj gönderdi',
}